# Generated by Django 5.2.5 on 2025-08-15 03:32

from django.db import migrations, models

class Migration(migrations.Migration):
    """
    ============================================================
                 MIGRAÇÃO DO BANCO DE DADOS
    ============================================================
    
    O QUE É UMA MIGRAÇÃO?
    - É um arquivo que descreve mudanças na estrutura do banco de dados
    - Funciona como controle de versão para o schema do banco
    - Permite evoluir a estrutura do BD sem perder dados existentes
    
    PARA QUE SERVE ESTA MIGRAÇÃO ESPECÍFICA?
    - Cria a tabela 'EmotionRecord' no banco de dados
    - Define a estrutura inicial da tabela que armazenará:
      * Registros de emoções detectadas
      * Timestamps automáticos
      * Imagens associadas às emoções
    
    COMO FOI GERADA?
    - Automaticamente pelo Django quando você executou:
      python manage.py makemigrations
    - O Django detectou o modelo EmotionRecord em models.py
    - Gerou este arquivo com instruções para criar a tabela correspondente
    
    COMO EXECUTAR?
    - Para aplicar esta migração ao banco de dados:
      python manage.py migrate
      
    ============================================================
    """

    initial = True  # Indica que esta é a migração inicial para este app

    dependencies = [
        # Migrações das quais esta depende (vazia = nenhuma dependência)
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionRecord',
            fields=[
                # ID automático (chave primária)
                ('id', models.BigAutoField(
                    auto_created=True, 
                    primary_key=True, 
                    serialize=False, 
                    verbose_name='ID'
                )),
                
                # Data/hora automática da criação do registro
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                
                # Campo para armazenar a emoção detectada (ex: "feliz", "triste")
                ('emotion', models.CharField(max_length=50)),
                
                # Campo para armazenar a imagem associada (opcional)
                ('image', models.ImageField(
                    blank=True,       # Permite campo vazio no formulário
                    null=True,        # Permite NULL no banco de dados
                    upload_to='frames/'  # Diretório onde as imagens serão salvas
                )),
            ],
        ),
    ]